name: Update GitHub Activity

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    name: Update activity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update GitHub Activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "chore: update recent activity [skip ci]"
          EMPTY_COMMIT_MSG: "chore: keep activity workflow active [skip ci]"
          MAX_LINES: 8

